In [28]:
import torch
import numpy as np

x = torch.FloatTensor(np.array([[1 , 2 , 4],[3 , 4 , 5]])) #It is always better to use 32 Bits then the 64 as It takes half the computation and Speed
x

tensor([[1., 2., 4.],
        [3., 4., 5.]])

In [29]:
x[: , 1] = -1

In [30]:
x.relu_() #In place Operation

tensor([[1., 0., 4.],
        [3., 0., 5.]])

In [31]:
device = "cuda"
x = x.to(device=device)
x.device

device(type='cuda', index=0)

In [52]:
#Putting
learning_rate = 0.1
x = torch.tensor(5.0 , requires_grad=True)
for iteration in range(100):
    f = x**2
    f.backward()
    with torch.no_grad():
        x -=  learning_rate * x.grad
    x.grad.zero_()

In [32]:
#Implementing Linear Regression using Pytorch
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
import torch

housing = fetch_california_housing()
x = housing.data
y = housing.target

In [33]:
x_train , x_test , y_train , y_test = train_test_split(x , y , random_state=42)
x_train , x_valid , y_train , y_valid = train_test_split(x_train , y_train , random_state=42)

In [34]:
x_train = torch.FloatTensor(x_train)
x_valid = torch.FloatTensor(x_valid)
x_test = torch.FloatTensor(x_test)

In [35]:
means = x_train.mean(dim= 0 , keepdim=True)
std = x_train.std(dim=0 , keepdim=True)
x_train = (x_train - means) / std
x_test = (x_test - means ) / std
x_valid = (x_valid - means) / std

In [36]:
y_train = torch.FloatTensor(y_train.reshape(-1 , 1))
y_test = torch.FloatTensor(y_test.reshape(-1 , 1))
y_valid = torch.FloatTensor(y_valid.reshape(-1 , 1))

In [37]:
torch.manual_seed(42)
n_featurs = x_train.shape[1]
w = torch.randn((n_featurs , 1) , requires_grad=True) #Random weigth initiliation
b = torch.tensor(0.0 , requires_grad=True) #Bias Term

In [41]:
learning_rate = 0.4
epochs = 20
for iterations in range(epochs):
    y_pred = x_train @ w + b #Forward Pass 
    loss = ((y_pred - y_train)** 2).mean()
    loss.backward() #Backward Pass
    with torch.no_grad():
        b -= learning_rate * b.grad
        w -= learning_rate * w.grad
        b.grad.zero_()
        w.grad.zero_()
    print(f"Epochs {iterations + 1} / {epochs} , Loss {loss.item()}")

Epochs 1 / 20 , Loss 0.529581606388092
Epochs 2 / 20 , Loss 0.5291473865509033
Epochs 3 / 20 , Loss 0.5287535190582275
Epochs 4 / 20 , Loss 0.5283960103988647
Epochs 5 / 20 , Loss 0.5280712246894836
Epochs 6 / 20 , Loss 0.5277760028839111
Epochs 7 / 20 , Loss 0.527507483959198
Epochs 8 / 20 , Loss 0.5272631049156189
Epochs 9 / 20 , Loss 0.5270405411720276
Epochs 10 / 20 , Loss 0.5268377065658569
Epochs 11 / 20 , Loss 0.5266526937484741
Epochs 12 / 20 , Loss 0.526483952999115
Epochs 13 / 20 , Loss 0.5263298153877258
Epochs 14 / 20 , Loss 0.5261890888214111
Epochs 15 / 20 , Loss 0.5260604023933411
Epochs 16 / 20 , Loss 0.5259426832199097
Epochs 17 / 20 , Loss 0.5258350372314453
Epochs 18 / 20 , Loss 0.5257365107536316
Epochs 19 / 20 , Loss 0.5256461501121521
Epochs 20 / 20 , Loss 0.5255633592605591


In [ ]:
#Prediction
x_new = x_test[:3]
with torch.no_grad():
    y_pred = x_new @ w + b

print(y_pred)

tensor([[0.7283],
        [1.7674],
        [2.7748]])
